### ISSUE TITLE
Bluetooth Module Location

### ISSUE THREAD

**Issue by olliegg123** [kcapp/smartboard#4]
Have you managed to locate where the Bluetooth module is on the board? Is it within the button section? I've seen these boards converted to USB so I'm wondering how it's done.

**Comment by thordy** [comment]
Hi @olliegg123 ,
I've not specifically located the Bluetooth module, but also not looked for it.
Did a tear down of a board at one point which you can see [on the Wiki](https://github.com/kcapp/smartboard/wiki/Board-Hardware)

If you want any specific pictures, or specifications from the board, let me know and I can see what I can provide

**Comment by olliegg123** [comment]
I saw the teardown, I've also managed to get myself a board too but not inspected it properly yet. On the ones modified to use USB, there is no button or magnetising section on the front - so the button section is completely removed. This made me wonder whether the button has the communication module within it (This would also make sense to me too because then there would be nothing blocking BLE communication i.e. the bristle board itself)

I wonder if I could communicate through the 4 pin blue/white cable connectors....

Check out this diagram that they publish:

<img width="597" alt="Screenshot 2021-07-18 at 19 48 23" src="https://user-images.githubusercontent.com/12632906/126078881-399324d1-af53-4ce7-8e4d-8008264d4f71.png">

**Comment by thordy** [comment]
@olliegg123 Did some more work on this today, and managed to find the Bluetooth chip in both V1 and V2 versions of the board. I updated the [Wiki page](https://github.com/kcapp/smartboard/wiki/Board-Hardware#bluetooth-chip-cc2541) with additional information which I hope can be useful to you.

In summary, the bluetooth chip is a [Texas Instruments CC2541](https://www.ti.com/product/CC2541), and it sits either inside the "main" component, or in the back of the board, so it's not located anywhere close to the button.

Unfortunately I don't have much experience with this low level chip, so not sure how it would be best to go about getting this wired onto USB, but please keep me updated if you move forward with this plan!

**Comment by olliegg123** [comment]
Thanks for working that out! Interesting though... I tried to use my board this weekend with the standard Unicorn app and it was pretty dreadful - constant disconnections. I'll look into the chip though, see if I can work out some way to interact with it through USB.

**Comment by thordy** [comment]
Similar experience I had, but connecting it to power and using my own implementation worked fairly well.
Please keep me update on what you are able to figure out regarding wiring the board, I'll close this issue for now
